=== AntoniaR/tkp/tkp/classification/manual/classification.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://transientskp.org/classification">

  <xs:complexType name="valueType">
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="special" />
                <xs:enumeration value="bool" />
                <xs:enumeration value="integer" />
                <xs:enumeration value="float" />
                <xs:enumeration value="string" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="unit" type="xs:string" />
	</xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="weightType">
      <xs:simpleContent>
        <xs:extension base="xs:float">
          <xs:attribute name="type">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="weight" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
	</xs:extension>
      </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="actionType">
    <xs:choice>
      <xs:element name="weight" type="weightType" />
      <xs:element name="branch" type="branchType" />
    </xs:choice>
  </xs:complexType>

  <xs:element name="operators" type="operatorType" />

  <xs:complexType name="operatorType">
    <xs:choice>
      <xs:element name="node" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="operatorType2">
    <xs:choice>
      <xs:element name="operator">
        <xs:complexType>
          <xs:all>
            <xs:element type="operatorType" name="operator1" />
            <xs:element type="operatorType" name="operator2" />
          </xs:all>
          <xs:attribute name="op" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="and" />
                <xs:enumeration value="or" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:complexType>
      </xs:element>

      <xs:element name="operator">
        <xs:complexType>
          <xs:all>
            <xs:element name="attribute" type="xs:string" />
            <xs:element name="value" type="valueType" />
          </xs:all>
          <xs:attribute name="op" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="gte" />
                <xs:enumeration value="lte" />
                <xs:enumeration value="gt" />
                <xs:enumeration value="lt" />
                <xs:enumeration value="eq" />
                <xs:enumeration value="neq" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:complexType>
      </xs:element>

      <xs:element name="operator">
        <xs:complexType>
          <xs:all>
            <xs:element name="attribute" type="xs:string" />
            <xs:element name="type" type="xs:string" />
            <xs:element name="unit" type="xs:string" />
          </xs:all>
          <xs:attribute name="op" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="match" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="precision" type="xs:float" />
        </xs:complexType>
      </xs:element>

    </xs:choice>
  </xs:complexType>

  <xs:complexType name="testType">
    <xs:sequence>
      <xs:element name="condition">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="variable" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="compare" type="operatorType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="outcome" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="value" type="valueType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="action" type="actionType" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>


  <xs:complexType name="branchType">
    <xs:sequence>
      <xs:element name="test" type="testType" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded" />

        <xs:element name="test" type="testType" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="transient-classification-scheme" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="branch" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                </xs:complexType>
              </xs:element>
              <xs:element name="test" type="testType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="id" type="xs:string" />
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AntoniaR/tkp/tkp/classification/manual/classification.xml
<?xml version="1.0" encoding="UTF-8" ?>

<root xmlns="http://transientskp.org/classification"
      schemaLocation="http://transientskp.org/svn/code/classification/classification.xsd">

  <comment>Needs check: can I use dashes for tag names? Can I use colons inside id attributes?</comment>

  <test id="test:GRB-prompt-emission-light-curve-duration" name="light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="and">
        <compare op="gt">
          <attribute>duration</attribute>
          <value type="float" unit="second">1.0e-1</value>
        </compare>
        <compare op="lte">
          <attribute>duration</attribute>
          <value type="float" unit="second">1.0e3</value>
        </compare>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.5</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:GRB-prompt-emission-light-curve-variability" name="light curve variability">
    <condition>
      <variable>self</variable>
      <compare op="lt">
        <attribute>variability</attribute>
        <value type="float">1.0e-1</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.5</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:GRB-prompt-emission-external-trigger-match" name="external trigger match">
    <condition>
      <variable>external-trigger</variable>
      <compare op="and">
        <compare op="match" precision="5">
          <attribute>position</attribute>
          <type>position</type>
          <unit>arcsec</unit>
        </compare>
        <compare op="match" precision="60">
          <attribute>timezero</attribute>
          <type>datetime</type>
          <unit>second</unit>
        </compare>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">1.0</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:GRB-reverse-shock-light-curve-duration" name="light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="and">
        <compare op="gt">
          <attribute>duration</attribute>
          <value type="float" unit="second">1.0e3</value>
        </compare>
        <compare op="lte">
          <attribute>duration</attribute>
          <value type="float" unit="second">1.0e6</value>
        </compare>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.5</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>
  
  <test id="test:GRB-reverse-shock-light-curve-variability" name="light curve variability">
    <condition>
      <variable>self</variable>
      <compare op="gt">
        <attribute>variability</attribute>
        <value type="float" unit="second">1.0e4</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.5</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>
     
  <test id="test:GRB-reverse-shock-external-trigger-match" name="external trigger match">
    <condition>
      <variable>external-trigger</variable>
      <compare op="and">
        <compare op="match" precision="5">
          <attribute>position</attribute>
          <type>position</type>
          <unit>arcsec</unit>
        </compare>
        <compare op="match" precision="1.0e4">
          <attribute>timezero</attribute>
          <type>datetime</type>
          <unit>second</unit>
        </compare>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.8</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:GRB-forward-shock-database-match" name="Database match">
    <condition>
      <variable>database</variable>
      <compare op="and">
        <compare op="eq">
          <attribute>association</attribute>
          <value type="bool">true</value>
        </compare>
        <compare op="eq">
          <attribute>name</attribute>
          <value type="string">GRB_afterglows</value>
        </compare>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.99</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>
  
  <test id="test:GRB-forward-shock-lightcurve-variability" name="Lightcurve variability">
    <condition>
      <variable>self</variable>
      <compare op="gt">
        <attribute>variability</attribute>
        <value type="float" unit="second">1.0e6</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">0.5</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:inverted-spectrum-anything" name="anything with an inverted spectrum">
    <condition>
      <variable>self</variable>
      <compare op="eq">
        <attribute>nonexistent</attribute>
        <value type="bool">false</value>
      </compare>
    </condition>
    <outcome>
      <value type="special">N/A</value>
      <action type="weight">1.0</action>
    </outcome>
  </test>

  <test id="test:slow-light-curve-duration" name="light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="gt">
        <attribute>duration</attribute>
        <value type="float" unit="second">0.98e3</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">1.0</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:fast-light-curve-duration" name="light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="lte">
        <attribute>duration</attribute>
        <value type="float" unit="second">1.0e3</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">1.0</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:slow-extended-source-light-curve-duration" name="extended light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="gt">
        <attribute>duration</attribute>
        <value type="float" unit="second">0.98e3</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">1.0</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>

  <test id="test:fast-extended-source-light-curve-duration" name="extended light curve duration">
    <condition>
      <variable>self</variable>
      <compare op="lte">
        <attribute>duration</attribute>
        <value type="float" unit="second">1.0e3</value>
      </compare>
    </condition>
    <outcome>
      <value type="bool">true</value>
      <action type="weight">1.0</action>
    </outcome>
    <outcome>
      <value type="bool">false</value>
      <value type="special">N/A</value>
      <action type="weight">0.0</action>
    </outcome>
  </test>


  <transient-classification-scheme>

   <classification id="classification:fast" name="Fast variable source">
     <rule>
       <type>weights</type>
       <test refer="test:fast-light-curve-duration" />
     </rule>
   </classification>

   <classification id="classification:slow" name="Slow variable source">
     <rule>
       <type>weights</type>
       <test refer="test:slow-light-curve-duration" />
     </rule>
   </classification>
  
    <branch name="point source" id="branch:point-source">
      <test name="point source">
        <condition>
          <variable>self</variable>
          <compare op="eq">
            <attribute>shape</attribute>
            <value type="string">point</value>
          </compare>
        </condition>
        <outcome>
          <value type="bool">true</value>
          <value type="special">N/A</value>
          <action type="branch">
            <branch name="positive spectrum" id="branch:positive-spectrum">
              <test name="positive-spectrum">
                <condition>
                  <variable>self</variable>
                  <compare op="gt">
                    <attribute>spectralslope</attribute>
